apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-service-nginx-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: loadbalancer-service-nginx-app
  template:
    metadata:
      labels:
        app: loadbalancer-service-nginx-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
