apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-test1-nginx-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: service-test1-nginx-app 
  template:
    metadata:
      labels:
        app: service-test1-nginx-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80 