apiVersion: v1
kind: Service
metadata:
  name: service-test1-nginx-service
spec:
  selector:
    app: service-test1-nginx-app  # Select Pods with the matching label
  ports:
    - protocol: TCP
      port: 80  # The port exposed by the Service
      targetPort: 80  # The port on the Pods to forward traffic to
  type: ClusterIP  # Default service type (internal only)