apiVersion: v1
kind: Service
metadata:
  name: node-port-service-nginx  # Service name following the node-port-service convention
spec:
  selector:
    app: node-port-service-nginx-app  # Selects Pods with the matching label
  ports:
    - protocol: TCP
      port: 80  # The port exposed by the Service
      targetPort: 80  # The port on the Pods to forward traffic to
      nodePort: 30080  # The static NodePort (optional; will auto-assign if not specified)
  type: NodePort  # Service type for external access